name: app
type: php:7.4
relationships:
  database:
    type: 'mysql'
    path: '/data/db'
    disk: 1024
web:
  commands:
    start: bin/start
    stop: bin/stop
  locations:
    '/':
      root: 'public'
      passthru: '/index.php'
      allow: true
