# The app's name, which must be unique within the project.
name: 'app'

# The language and version for your app.
type: 'symfony:6'

# The size of the app's persistent disk (in MB).
disk: 2048

web:
  locations:
    '/':
      root: 'public'
      index: 'index.php'
      try_files: '$uri /index.php$is_args$args'
      passthru: 'index.php'
      allow: true
      expires: -1
  env:
    DATABASE_URL: 'mysql://username:password@database/dbname'
  commands:
    start: bin/console server:start
    stop: bin/console server:stop

dependencies:
  post_deploy:
    - composer install
