# The app's name, which must be unique within the project.
name: 'app'

# The type key specifies the language and version for your app.
type: 'php:8.1'

# Global dependencies to be added and cached and then available as commands.
dependencies:
    php:
        composer/composer: '^2'


# Scripts that are run as part of the build and deploy process.
hooks:
    # Build hooks can modify app files on disk but not access any services like databases.
    build: ./build.sh
    # Deploy hooks can access services but the file system is now read-only.
    deploy: ./deploy.sh
    # Post deploy hooks run when the app is accepting outside requests.
    post_deploy: ./post_deploy.sh

# The size of the app's persistent disk (in MB).
disk: 2048

# Define writable, persistent filesystem mounts.
# The key is the directory path relative to the application root.
# In this case, `web-files` is just a unique name for the mount.
mounts:
    'web/files':
        source: local
        source_path: 'web-files'

# The app configuration when it's exposed to the web.
web:
    locations:
        '/':
            # The app's public directory relative to its root.
            root: 'public'
            # A front controller to determine how to handle requests.
            passthru: '/app.php'
        # Allow uploaded files to be served, but don't run scripts.
        # Missing files get sent to the front controller.
        '/files':
            root: 'web/files'
            scripts: false
            allow: true
            passthru: '/app.php'